### ISSUE TITLE
Ansible support for remote deployment of project

### ISSUE THREAD

**Issue by P0intMaN** [CYBERDEVILZ/Stock-Market-Prediction#2]
Hi @CYBERDEVILZ , I am putting forth an idea to use ansible to do a Continuous Deployment of this application to remote servers. Would you like to take this up as an issue?

**Comment by CYBERDEVILZ** [comment]
Would you mind telling me about the specifics of the server you are going to use. Might be of great help.

**Comment by P0intMaN** [comment]
The server will be a linux based OS. Will be installing tomcat and other services in it. We would be using servers from Azure

**Comment by CYBERDEVILZ** [comment]
Amazing. Waiting for your PR 😄

**Comment by P0intMaN** [comment]
Tracking ansible code changes here:
- #3 
- #4 
- #5 
- #6

**Comment by P0intMaN** [comment]
Could you add hacktoberfest label on this issue please? I would like them to be counted for hacktoberfest contest

**Comment by CYBERDEVILZ** [comment]
All PRs have been merged! Amazing stuff @P0intMaN.
Thanks for keeping this repo clean and updated!
